//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBayService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxDetail
    {
        public int ID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<System.DateTime> InboxDate { get; set; }
        public string Content { get; set; }
    }
}
