//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBayService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInbox
    {
        public int MessageID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OwnerID { get; set; }
    }
}
