//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBayService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStatistic
    {
        public int Id { get; set; }
        public int BillID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> NumberOf { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    }
}
