//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBayService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string KiotNo { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public int MarketID { get; set; }
        public int OwnerID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string SasQuery { get; set; }
    }
}
